---
title: π-calculus and Interaction Nets
subtitle: there and back again
tags: Programming languages, Concurrency, Asynchrony, Interaction nets
---

== Recursion vs Replication
In the π-calculus replication suffices to replace recursively-defined
terms.  But this is only because connections in the π-calculus are
_inherently_ recursive: a replicated term can refer to another copy of
itself by using a channel it shares with that copy.  Without this
capability, e.g. in the private π-calculus, replication does not
suffice to reproduce recursion.

[#pi-calculus]
== π-calculus
There are many variants of the π-calculus.  The variant discussed here
has replication and restriction.



[pikchr,svg-type="inline",role="mono"]
.The interaction rule for duplication in the interaction combinators, where stem:[δ] is the duplicating agent and stem:[ζ] is an agent to be duplicated.
....
define agent {
  # width height label
  A: line up $2 right $1/2 \
    then left $1 rad 20px \
    then down $2 right $1/2 \
    close
  text at 0.10*$2 above A.c $3 big big
}

Arrow: move right 1.5cm
line from 0.2cm above Arrow.start to 0.2cm left of 0.2cm above Arrow.end
line from 0.2cm below Arrow.start to 0.2cm left of 0.2cm below Arrow.end
line from 0.4cm above 0.4cm left of Arrow.end to Arrow.end \
  then to 0.4cm below 0.4cm left of Arrow.end

move from Arrow.start left 1.5cm up 0.5cm
G1: [agent(2cm, 1.5cm, "δ")]
dot at 0.4cm left of G1.n
line up 1cm
dot at 0.4cm right of G1.n
line up 1cm

move from Arrow.start left 1.5cm down 0.5cm
Z1: [agent(2cm, -1.5cm, "ζ")]
dot at 0.4cm left of Z1.s
line down 1cm
dot at 0.4cm right of Z1.s
line down 1cm

line from G1.s to Z1.n

Centre: dot at 3cm right of Arrow.end invis

move from Centre left 1.5cm up 1.5cm
Z2: [agent(2cm, -1.5cm, "ζ")]
Z2pax1: dot at 0.4cm right of Z2.s
Z2pax2: dot at 0.4cm left of Z2.s

move from Centre right 1.5cm up 1.5cm
Z3: [agent(2cm, -1.5cm, "ζ")]
Z3pax1: dot at 0.4cm right of Z3.s
Z3pax2: dot at 0.4cm left of Z3.s

move from Centre left 1.5cm down 1.5cm
G2: [agent(2cm, 1.5cm, "δ")]
G2pax1: dot at 0.4cm left of G2.n
G2pax2: dot at 0.4cm right of G2.n

move from Centre right 1.5cm down 1.5cm
G3: [agent(2cm, 1.5cm, "δ")]
G3pax1: dot at 0.4cm left of G3.n
G3pax2: dot at 0.4cm right of G3.n

spline from Z2pax2 to G2pax1
spline from Z2pax1 down 1cm then to 1cm above G3pax1 then down 1cm
spline from Z3pax2 down 1cm then to 1cm above G2pax2 then down 1cm
spline from Z3pax1 to G3pax2

line from Z2.n up 1cm
line from Z3.n up 1cm
line from G2.s down 1cm
line from G3.s down 1cm
....

// Unfortunately KaTeX doesn't support setting \arraycolsep so we must
// remove spacing manually here with \hspace.

[stem]
++++
\def\arrayop#1{\hspace{-0.5em}&\mathbf{#1}&\hspace{-0.5em}}
\def\defeq{\arrayop{::=}}
\def\alt{\arrayop{|}}
\begin{array}{rrl}
  P \defeq 0\\
    \alt P \mid Q\\
    \alt x(y). P\\
    \alt \bar{x}\\
    \alt (νx). P\\
    \alt !P
\end{array}
++++

[source,subs="+quotes"]
----
P ::=
P *::=* 0          end
    *|* P | Q      parallel composition
    *|* x(y). P    read y from x, then continue as P
    *|* ̅x⟨y⟩. P    write y to x, then continue as P
    *|* (νx). P    restrict the name x to P
    *|* !P         replication
----

[#asynchronous-pi-calculus]
== Asynchronous π-calculus
One simplification we can make is to remove the notion of output prefixing.  This

== Fusion Calculus

== Notes

Introduction to π calculus.  Difference from λ-calculus:
- return values → ⊥
- λ → ν + reading
- semantics of multiple writes: copy closure → multiple reads within closure

Imagine encoding of λ-calculus into π-calculus by reversing these:
- λ → ν + !(read + body)
- @ → write

Synchronous π-calculus → asynchronous π-calculus: remove output prefixing
Asynchronous π-calculus → fusion calculus: input prefixing → fusion
? fusion contains sync or async π?

Fusion calculus → solos calculus
Solos calculus is asynchronous fusion calculus
